# Functional Labels for speach learning

In [1]:
import os
import mne
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats import multitest as mul

mne.viz.set_3d_options(antialias = False)

# Plot Median Wall

In [3]:
subjects_dir = '/net/server/data/Archive/prob_learn/freesurfer'

#read label 
label_rh = mne.read_label('/net/server/data/Archive/prob_learn/freesurfer/fsaverage/label/rh.Medial_wall.label', 'fsaverage' )
label_lh = mne.read_label('/net/server/data/Archive/prob_learn/freesurfer/fsaverage/label/lh.Medial_wall.label', 'fsaverage' )


In [4]:
print(label_rh)
print(label_lh)

<Label | fsaverage, 'rh.Medial_wall-rh', rh : 13916 vertices>
<Label | fsaverage, 'lh.Medial_wall-lh', lh : 13887 vertices>


# Download stc

In [5]:
stc = mne.read_source_estimate('/net/server/data/Archive/prob_learn/pultsinak/sources_sLoreta/averege_betwen_subj/pos_neg_1500_1900/after_fb_lp_pos_vs_neg_mean_beta_1500_1900', 'fsaverage')



In [6]:
stc

<SourceEstimate | 20484 vertices, subject : fsaverage, tmin : 1705.0 (ms), tmax : 1705.0 (ms), tstep : 410.0 (ms), data shape : (20484, 1), ~240 kB>

In [7]:
stc.data

array([[1.2605672 ],
       [0.42016888],
       [0.84528816],
       ...,
       [0.4427604 ],
       [0.46901032],
       [0.52857256]], dtype=float32)

In [8]:
len(stc.data)

20484

# Plot stc on brain

In [10]:
scale = [0.95, 0.99, 1.0]

brain = mne.viz.plot_source_estimates(stc, hemi='split', views = ['lat', 'med'], time_viewer='auto', initial_time = -1.950,
                                            clim = dict(kind = 'value', pos_lims = scale),
                                           spacing ='ico5')


Using pyvistaqt 3d backend.



QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-vtretyakova'


# Applying labels

In [11]:
len(label_rh.vertices)

13916

In [12]:
label_rh.vertices

array([    27,     28,     37, ..., 161377, 161378, 161379])

https://mne.tools/stable/generated/mne.SourceEstimate.html#mne.SourceEstimate.in_label

In [25]:

# hemi separate
stc_in_label_lh = stc.in_label(label_lh) 
stc_in_label_rh = stc.in_label(label_rh) 


# both hemi
#both_hemi_labels = mne.BiHemiLabel(label_lh, label_rh)
#stc_in_label = stc.in_label(both_hemi_labels) #BiHemiLabel


In [16]:
stc_in_label

<SourceEstimate | 1742 vertices, subject : fsaverage, tmin : 1705.0 (ms), tmax : 1705.0 (ms), tstep : 410.0 (ms), data shape : (1742, 1), ~21 kB>

In [18]:
# plot labels in both hemi

brain = mne.viz.plot_source_estimates(stc_in_label, hemi='split', views = ['lat', 'med'], time_viewer='auto', background = 'white', clim = dict(kind = 'value', lims = scale),
                                           spacing ='ico5')
brain.add_label(label_lh, color = 'green', borders=True) # border - show borders or not

brain.add_label(label_rh, color = 'red', borders=True) # border - show borders or not




In [37]:
list_of_index_lh = stc_in_label_lh.vertices[0].tolist()
list_of_index_rh = stc_in_label_rh.vertices[1].tolist()

In [39]:
list_of_index_rh

[27,
 28,
 37,
 60,
 80,
 81,
 82,
 123,
 124,
 125,
 126,
 128,
 147,
 151,
 201,
 269,
 270,
 271,
 272,
 273,
 280,
 282,
 283,
 324,
 330,
 331,
 332,
 333,
 334,
 395,
 396,
 397,
 398,
 432,
 433,
 434,
 435,
 436,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 547,
 548,
 598,
 599,
 607,
 608,
 610,
 611,
 749,
 750,
 751,
 753,
 760,
 761,
 762,
 763,
 810,
 811,
 812,
 813,
 814,
 815,
 899,
 900,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1209,
 1210,
 1211,
 1212,
 1213,
 1330,
 1331,
 1332,
 1333,
 1334,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1512,
 1513,
 1514,
 1515,
 1516,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1659,
 1660,
 1661,
 1662,
 1663,
 1736,
 1746,
 1747,
 1748,
 1749,
 1750,
 1751,
 1752,
 1753,
 1754,
 1883,
 1884,
 1885,
 1886,
 

In [40]:
list_of_index_lh

[8,
 36,
 38,
 78,
 79,
 113,
 144,
 145,
 146,
 147,
 148,
 160,
 161,
 198,
 199,
 314,
 315,
 316,
 325,
 326,
 327,
 328,
 329,
 354,
 355,
 356,
 358,
 430,
 431,
 447,
 448,
 503,
 504,
 505,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 598,
 599,
 600,
 601,
 602,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 677,
 678,
 679,
 794,
 795,
 796,
 805,
 806,
 807,
 808,
 809,
 834,
 835,
 836,
 955,
 956,
 957,
 958,
 959,
 967,
 984,
 985,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1313,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1344,
 1345,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1510,
 1511,
 1718,
 1719,
 1720,
 1721,
 1722,
 1728,
 1737,
 1738,
 1739,
 1740,
 1741,
 1742,
 1743,
 1744,
 1745,
 1788,
 1789,
 1790,
 1791,
 1792,
 1794,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 2001,
 200

In [28]:
stc.vertices[0] # left hemispere

array([    0,     1,     2, ..., 10239, 10240, 10241])

In [45]:
stc.vertices[1] # right hemispere

array([    0,     1,     2, ..., 10239, 10240, 10241])

In [29]:
print(stc.data.shape)
print(stc.rh_data.shape)

(20484, 1)
(10242, 1)


In [30]:
stc_lh_reshape = np.reshape(stc.lh_data, 10242) # left hemi
stc_rh_reshape = np.reshape(stc.rh_data, 10242) # right hemi
#stc_reshape = np.reshape(stc.data, 20484) # both hemi

In [31]:
stc_rh_reshape.shape #only right hemi
#stc_reshape.shape

(10242,)

In [41]:
#only right hemi
'''
for i in stc.vertices[1]:
    if i in list_of_index:
        stc_rh_reshape[i] = 0
'''
# both hemi
hemisphere = [0,1]
indexes = [list_of_index_lh, list_of_index_rh]
stc_reshape_hemi = [stc_lh_reshape, stc_rh_reshape]
for i in hemisphere:
    for j in stc.vertices[i]:
        if j in indexes[i]:
            stc_reshape_hemi[i][j] = 0
        

In [42]:
stc_rh_reshape[1516]

0.0

In [43]:
stc_lh_reshape[1422]

0.0

In [45]:
type(stc_rh_reshape)

numpy.ndarray

In [46]:
stc_rh_new = stc_rh_reshape.reshape((10242, 1))
stc_rh_new.shape

(10242, 1)

In [73]:
stc_rh_new

array([[0.79488397],
       [0.9918169 ],
       [0.3155215 ],
       ...,
       [0.4427604 ],
       [0.46901032],
       [0.52857256]], dtype=float32)

In [47]:
stc_lh_new = stc_lh_reshape.reshape((10242, 1))
stc_lh_new.shape

(10242, 1)

In [48]:
stc.data[:10242] = stc_lh_new
stc.data[10242:] = stc_rh_new


In [50]:
scale = [0.95, 0.99, 1.0]
brain = mne.viz.plot_source_estimates(stc, hemi='split', views = ['lat', 'med'], 
                                      time_viewer='auto', clim = dict(kind = 'value', lims = scale))      
